### ISSUE TITLE
Problem Text Flickers

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#13]
Hello Brian ,
How are you ?

I am doing some test with differents texts and logos on a 128*128 LED panels

I notice that when there are some fixed text or logo (TextAnimations.On() method  for exemple ) ,
the text or logo Flickers

I try to change FPS but no change ..

How i can resolve this problem ?

with scolling text i have not noticed any flickers problems , it's strange ..

I don't remenber but with older versions of your lib i have not seen this problem earlier ..

 there is no problem on the windows simulator

can you help me please ?

Regards , Valentin

**Comment by BNNorman** [comment]
The fact it doesn't happen with other text animations suggests it's the coding of the On animation.
Could you try recoding it as below so it only calls self.DrawText() when the animation is initialised and let me know if it fixes it. If so I'll push the changes to github.

I have to confess that although I wrote it I didn't really test it. (Slapped wrist)


```
class On(TextAnimBase):
    """
   On simply displays the given text message until the duration expires
    """
   def step(self):
        if self.init:
              self.drawText()
       self.refreshCanvas()
```

**Comment by BNNorman** [comment]
Darn - the python indents disappeared after I posted.
I have updated the comment.

**Comment by ValDY69** [comment]
thanks brian for your quick answer !

but unlucky it's not working with this change 
it seems that it's a little bit more flickers ...

**Comment by BNNorman** [comment]
Ok, it is related to the foreground colour - if you set the foreground to a single colour there's no flickering. If you use a palette what happens is the code redraws the text using the next color in the list when the animation resets. The reason the simulator doesn't show this effect is that it can run much faster than the physical panel hence the effect is less noticeable.
I'll have a look at the rendering code to see if I can find out why multicolored palettes do this when they should only change the color when the animation duration is over.

**Comment by BNNorman** [comment]
Fixed - whoops, forgot to make self.init False
```
class On(TextAnimBase):
    """
   On simply displays the given text message until the duration expires
    """
   def step(self):
        if self.init:
              self.drawText()
              self.init=False        <--- missing line
       self.refreshCanvas()
```

Was steady on my panel after the missing line was added. I have pushed it to github

**Comment by ValDY69** [comment]
i test your new code now and no change ... the problem is still here

**Comment by BNNorman** [comment]
Very odd, it worked on my panel. Did you edit your copy or download the updated TextAnimations.py?

**Comment by ValDY69** [comment]
i edit my copy with your modif in this issue + OFFmultiColored = False


class On(TextAnimBase):
    """
   On simply displays the given text message until the duration expires
    """
   def step(self):
        if self.init:
              self.drawText()
              self.init=False        <--- missing line
       self.refreshCanvas()

--------------------------------


    #multiColored=False  # now in the text object
    OFFmultiColored = False  # depracated, now in the text object

**Comment by ValDY69** [comment]
i precise that this problem is not really visible for me an a 64*64 led panels but much more present on a bigger screen like 128*128 !
